name: Python CI

on:
  push:
    branches: [ main, ch/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx libglib2.0-0

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev --deploy

      - name: Verify critical packages
        run: |
          pipenv run python -c "import sys; print(f'Python: {sys.version}')"
          pipenv run python -c "import cv2; print(f'OpenCV: {cv2.__version__}')"
          pipenv run python -c "import mediapipe; print(f'MediaPipe: {mediapipe.__version__}')"
          pipenv run python -c "import pygame; print(f'PyGame: {pygame.version.ver}')"
          pipenv run python -c "import numpy; print(f'NumPy: {numpy.__version__}')"
          pipenv run python -c "import tensorflow; print(f'TensorFlow: {tensorflow.__version__}')"

      - name: Run basic syntax check
        run: |
          pipenv run python -m py_compile *.py || echo "No .py files in root"
          find . -name "*.py" -exec pipenv run python -m py_compile {} \; || echo "No additional .py files found"

      - name: Check for basic linting issues
        run: |
          find . -name "*.py" -exec pipenv run python -c "import ast; ast.parse(open('{}').read())" \; 2>/dev/null || echo "No .py files found to parse"
